# Generated by Django 2.1.7 on 2019-03-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180616_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest1', models.CharField(max_length=127)),
                ('interest2', models.CharField(max_length=127)),
                ('interest3', models.CharField(max_length=127)),
                ('interest4', models.CharField(max_length=127)),
                ('interest5', models.CharField(max_length=127)),
            ],
        ),
    ]
