# Generated by Django 2.1.7 on 2019-03-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_interests_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests_m',
            name='user',
            field=models.CharField(default='No Name', max_length=127),
        ),
    ]
