# Generated by Django 2.1.7 on 2019-03-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_interests_m_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests_m',
            name='email',
            field=models.CharField(default='No Email', max_length=127),
        ),
    ]
